Delete CODE_OF_CONDUCT.md
crablang/crab pull request #34
Opened 2023-04-18 14:28 UTC by wooky

It is too deeply intertwined with the-language-that-shall-not-be-named.

2023-04-19 19:19 UTC, jpmcb requested changes
I think better-yet, having a `crablang` specific code of conduct makes the most sense. Can delete for now, but would be best for this community to define its own conduct standards.

It would be a mistake to go on without a code of conduct.

2023-04-20 00:45 UTC, zigster64 commented
I agree

The sooner you can purge the codebase of anything political, the sooner the bike shedding can end, and the coding begin

2023-04-20 19:38 UTC, dcow commented
Also if it does come back please name it something else like Conduct Policy or something that doesn't get an acronym that sounds like 🍆

2023-04-22 19:46 UTC, trvswgnr commented
let's discuss this more. closing for now.

2023-04-22 19:46 UTC, closed without merging

2023-06-11 21:12 UTC, catkira commented
why close?